name: pic-2-table

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.6
  - pandas
  - matplotlib
  - seaborn
  - transformers
  - huggingface_hub
  - python-dotenv
  - autopep8
  - pylint
  - pip
  - pip:
      - timm
      - torch 
      - torchvision 
      - torchaudio